//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Sargent and Greenleaf")]
[assembly: System.Reflection.AssemblyProduct("Sargent and Greenleaf Lock Management API")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2014. All rights reserved.")]
[assembly: System.Reflection.AssemblyVersion("1.0.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.1.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "Sargent and Greenleaf";
    
    internal const string AssemblyProduct = "Sargent and Greenleaf Lock Management API";
    
    internal const string AssemblyCopyright = "Copyright © 2014. All rights reserved.";
    
    internal const string AssemblyVersion = "1.0.1.0";
    
    internal const string AssemblyFileVersion = "1.0.1.0";
    
    internal const string AssemblyInformationalVersion = "1.0.1.0";
    
    private ThisAssembly() {
    }
}
