//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaG.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaG.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication code..
        /// </summary>
        public static string API_InvalidAuthCode {
            get {
                return ResourceManager.GetString("API.InvalidAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API client credentials..
        /// </summary>
        public static string API_InvalidCredentials {
            get {
                return ResourceManager.GetString("API.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} has an invalid value..
        /// </summary>
        public static string ArgumentException_Error {
            get {
                return ResourceManager.GetString("ArgumentException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client_Link_Text {
            get {
                return ResourceManager.GetString("Client.Link.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sargent and Greenleaf.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2014.
        /// </summary>
        public static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate operation code..
        /// </summary>
        public static string DuplicateOperationCodeException_Error {
            get {
                return ResourceManager.GetString("DuplicateOperationCodeException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired authentication token..
        /// </summary>
        public static string Error_InvalidExpiredToken {
            get {
                return ResourceManager.GetString("Error.InvalidExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid authentication token header..
        /// </summary>
        public static string Error_InvalidTokenHeader {
            get {
                return ResourceManager.GetString("Error.InvalidTokenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator is not allowed to access this resource..
        /// </summary>
        public static string Error_OperatorPriorityAccess {
            get {
                return ResourceManager.GetString("Error.OperatorPriorityAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Link_Text {
            get {
                return ResourceManager.GetString("Help.Link.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lock status..
        /// </summary>
        public static string InvalidLockStatException_Error {
            get {
                return ResourceManager.GetString("InvalidLockStatException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation date..
        /// </summary>
        public static string InvalidOperationDateException_Error {
            get {
                return ResourceManager.GetString("InvalidOperationDateException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation date range..
        /// </summary>
        public static string InvalidOperationDateRangeException_Error {
            get {
                return ResourceManager.GetString("InvalidOperationDateRangeException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation hour..
        /// </summary>
        public static string InvalidOperationHourException_Error {
            get {
                return ResourceManager.GetString("InvalidOperationHourException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation hour limit..
        /// </summary>
        public static string InvalidOperationHourLimitException_Error {
            get {
                return ResourceManager.GetString("InvalidOperationHourLimitException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid touch key position..
        /// </summary>
        public static string InvalidTouchKeyPositionException_Error {
            get {
                return ResourceManager.GetString("InvalidTouchKeyPositionException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password..
        /// </summary>
        public static string Login_EnterPassword {
            get {
                return ResourceManager.GetString("Login.EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username..
        /// </summary>
        public static string Login_EnterUsername {
            get {
                return ResourceManager.GetString("Login.EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string Login_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Login.InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Text {
            get {
                return ResourceManager.GetString("Login.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_Text {
            get {
                return ResourceManager.GetString("Logout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management_Link_Text {
            get {
                return ResourceManager.GetString("Management.Link.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Login.
        /// </summary>
        public static string OperatorLogin_Text {
            get {
                return ResourceManager.GetString("OperatorLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_Text {
            get {
                return ResourceManager.GetString("Password.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Management.
        /// </summary>
        public static string System_Name {
            get {
                return ResourceManager.GetString("System.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have encountered an unhandled exception..
        /// </summary>
        public static string Unhandled_Error {
            get {
                return ResourceManager.GetString("Unhandled.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user level..
        /// </summary>
        public static string UserLevelException_Error {
            get {
                return ResourceManager.GetString("UserLevelException.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username_Text {
            get {
                return ResourceManager.GetString("Username.Text", resourceCulture);
            }
        }
    }
}
